FROM registry.access.redhat.com/ubi9/ubi-init

RUN dnf update -y && dnf install -y \
  libcap-devel \
  pkg-config \
  systemd-devel \
  git \
  make \
  gcc \
  python3.12

RUN cd /tmp && \
  git clone https://github.com/ioi/isolate.git && \
  cd isolate && \
  make isolate && \
  make install

RUN mkdir /venvs
COPY server /tmp/server
COPY sandbox /tmp/sandbox
RUN python3.12 -m venv /venvs/server
RUN python3.12 -m venv /venvs/sandbox
RUN /venvs/server/bin/pip3 install /tmp/server/
RUN /venvs/sandbox/bin/pip3 install /tmp/sandbox/

RUN mkdir /pytools
RUN mkdir /sandbox

COPY services/server.service /etc/systemd/system/server.service
RUN systemctl enable server.service
RUN systemctl enable isolate.service
