FROM registry.access.redhat.com/ubi9/ubi-init

RUN dnf update -y && dnf install -y \
  libcap-devel \
  pkg-config \
  systemd-devel \
  git \
  make \
  gcc

RUN cd /tmp && \
  git clone https://github.com/ioi/isolate.git && \
  cd isolate && \
  make isolate && \
  make install

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN mkdir /venvs
COPY server /tmp/server
COPY sandbox /tmp/sandbox
RUN uv venv /venvs/server --python 3.11
RUN uv venv /venvs/sandbox --python 3.11
RUN uv pip install /tmp/server/ --python /venvs/server/bin/python
RUN uv pip install /tmp/sandbox/ --python /venvs/sandbox/bin/python

RUN mkdir /pytools
RUN mkdir /sandbox

COPY services/server.service /etc/systemd/system/server.service
RUN systemctl enable server.service
RUn systemctl enable isolate.service

ENTRYPOINT ["/sbin/init"]
